### ISSUE TITLE
charm gets stuck in `MaintenanceStatus` if `pebble-ready` even happens after `install`

### ISSUE THREAD

**Issue by ca-scribner** [canonical/kubeflow-profiles-operator#81] opened 2023-02-02 20:28 UTC
## Summary

During charm startup, if we any sequence of events where a pebble-ready is the last of the startup events to fire, for example:
* `kfam-pebble-ready`
* `install`
* `kubeflow-profiles-pebble-ready`

The charm gets stuck in `MaintenanceStatus` with a message "Profiles layer configured".  This is because [_on_kubeflow_profiles_ready()](https://github.com/canonical/kubeflow-profiles-operator/blob/e983aa03720df44231091ce6826071c06a5cf0e3/src/charm.py#L254) calls [_update_profiles_container()](https://github.com/canonical/kubeflow-profiles-operator/blob/e983aa03720df44231091ce6826071c06a5cf0e3/src/charm.py#L219) which, if it completes successfully, leaves the charm in [`MaintenanceStatus`](https://github.com/canonical/kubeflow-profiles-operator/blob/e983aa03720df44231091ce6826071c06a5cf0e3/src/charm.py#L232).  No event is guaranteed to occur after this that will change the status to active.  

The charm's workload and kubeflow as a whole are likely functioning properly here, but this is still an issue because:
* it is misleading to the user (anyone reading `juju status`)
* it causes our [CI to fail due to timeouts](https://github.com/canonical/kfp-operators/actions/runs/4068613873/jobs/7007378220#step:5:74), because our CI is waiting for everything to be active/idle before proceeding

## Proposed fix

We can refactor how we handle these events to make things more robust.  [seldon](https://github.com/canonical/seldon-core-operator/blob/main/src/charm.py) handles this differently, directing most events through a common `main` function.  This feels gross, but because of the interconnected nature of events it becomes easier to manage.  Another possible take on this is in this [draft profiles pr](https://github.com/canonical/kubeflow-profiles-operator/pull/69) which tried to make this more robust

**Comment by ca-scribner** [comment] 2023-02-02 21:37
This feels like something that could be caught by a set of unit tests that try all the different orders of possible startup hooks (eg [install, kfam-pebble-ready, kubeflow-profiles-pebble-ready], then [kfam, install, profiles] ...).  That would be helpful to catch things like this in the future

**Comment by DnPlas** [comment] 2023-02-03 18:38
This seems like a duplicate of #74, although the description is more detailed here, I am closing the issue as it is tracked already.

**Closed by DnPlas** 2023-02-03 18:38 UTC
Labels: bug
